"""Utility to update WhatsApp Gateway .env values"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Update WhatsApp Gateway .env configuration")
    parser.add_argument(
        "--env-file",
        default=Path(__file__).resolve().parent.parent / ".env",
        type=Path,
        help="Path to the .env file (default: whatsapp-gateway/.env)",
    )
    parser.add_argument("--access-token", dest="access_token", help="New Meta access token")
    parser.add_argument("--verify-token", dest="verify_token", help="Webhook verify token")
    parser.add_argument("--phone-number-id", dest="phone_number_id", help="WhatsApp phone number ID")
    parser.add_argument("--business-account-id", dest="business_account_id", help="WhatsApp Business Account ID")
    parser.add_argument("--api-version", dest="api_version", help="Meta Graph API version, e.g. v22.0")
    return parser.parse_args()


def load_env(path: Path) -> Dict[str, str]:
    data: Dict[str, str] = {}
    if not path.exists():
        return data
    for line in path.read_text("utf-8").splitlines():
        if not line or line.strip().startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip()
    return data


def write_env(path: Path, values: Dict[str, str]) -> None:
    ordered_keys = [
        "META_VERIFY_TOKEN",
        "META_ACCESS_TOKEN",
        "META_PHONE_NUMBER_ID",
        "META_BUSINESS_ACCOUNT_ID",
        "META_API_VERSION",
        "BACKEND_API_URL",
        "BACKEND_API_TIMEOUT",
        "APP_NAME",
        "APP_VERSION",
        "DEBUG",
        "LOG_LEVEL",
        "HOST",
        "PORT",
        "DEFAULT_TENANT_ID",
    ]
    lines = ["# Auto-generated by update_meta_env.py"]
    for key in ordered_keys:
        if key in values:
            lines.append(f"{key}={values[key]}")
    for key, value in sorted(values.items()):
        if key not in ordered_keys:
            lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", "utf-8")


def main() -> None:
    args = parse_args()
    env_path: Path = args.env_file
    env_values = load_env(env_path)

    if args.access_token:
        env_values["META_ACCESS_TOKEN"] = args.access_token
    if args.verify_token:
        env_values["META_VERIFY_TOKEN"] = args.verify_token
    if args.phone_number_id:
        env_values["META_PHONE_NUMBER_ID"] = args.phone_number_id
    if args.business_account_id:
        env_values["META_BUSINESS_ACCOUNT_ID"] = args.business_account_id
    if args.api_version:
        env_values["META_API_VERSION"] = args.api_version

    write_env(env_path, env_values)
    print(f"Updated {env_path}")


if __name__ == "__main__":
    main()

