"""Domain models related to messaging"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class MessageType(str, Enum):
    TEXT = "text"
    IMAGE = "image"
    AUDIO = "audio"
    VIDEO = "video"
    DOCUMENT = "document"
    STICKER = "sticker"
    LOCATION = "location"
    CONTACTS = "contacts"
    INTERACTIVE = "interactive"
    BUTTON = "button"
    UNKNOWN = "unknown"


class MessageDirection(str, Enum):
    INCOMING = "incoming"
    OUTGOING = "outgoing"


class NormalizedMessage(BaseModel):
    """Payload received from the WhatsApp Gateway"""

    message_id: str
    tenant_id: str = Field(..., description="Tenant responsible for the contact")
    phone_number: str
    phone_number_id: str
    display_phone_number: str
    contact_name: Optional[str] = None
    message_type: MessageType
    direction: MessageDirection = MessageDirection.INCOMING
    content: str
    raw_content: Optional[Dict[str, Any]] = None
    media_id: Optional[str] = None
    media_mime_type: Optional[str] = None
    timestamp: datetime
    metadata: Optional[Dict[str, Any]] = None


class FlowExecutionResult(BaseModel):
    """Result returned by the flow-engine"""

    handled: bool = False
    reply_text: Optional[str] = None
    session_state: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    requires_handoff: bool = False
    detected_intent: Optional[str] = None


class AIResponse(BaseModel):
    """Response generated by the AI engine"""

    handled: bool = True
    reply_text: str
    detected_intent: Optional[str] = None
    confidence: Optional[float] = None
    session_state: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None


class ConversationAction(BaseModel):
    """Action that the backend expects the gateway to perform"""

    source: str = Field(..., description="flow or ai")
    reply_text: str
    tenant_id: str
    phone_number: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    session_state: Dict[str, Any] = Field(default_factory=dict)
    requires_handoff: bool = False
    created_at: datetime = Field(default_factory=datetime.utcnow)

