-- Migration 008: Sales proposals
-- Stores commercial proposals generated by the super-admin team for incoming
-- leads. Includes recommended plan, recurring monthly value, setup fee and
-- additional items. PDFs are rendered on the frontend, the database keeps the
-- record of what was offered for auditing and conversion.

CREATE TABLE IF NOT EXISTS proposals (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    lead_id BIGINT UNSIGNED NULL,
    tenant_id BIGINT UNSIGNED NULL,
    company_name VARCHAR(190) NOT NULL,
    contact_name VARCHAR(160) NOT NULL,
    contact_email VARCHAR(190) NOT NULL,
    contact_whatsapp VARCHAR(32) NULL,
    plan VARCHAR(50) NOT NULL,
    monthly_value DECIMAL(10,2) NOT NULL,
    setup_fee DECIMAL(10,2) NOT NULL DEFAULT 0,
    monthly_message_limit INT UNSIGNED NOT NULL DEFAULT 1000,
    included_items JSON NULL,
    validity_days INT UNSIGNED NOT NULL DEFAULT 7,
    status ENUM('draft','sent','accepted','rejected') NOT NULL DEFAULT 'draft',
    notes TEXT NULL,
    created_by_user_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_proposals_status_created (status, created_at),
    KEY idx_proposals_lead (lead_id),
    CONSTRAINT fk_proposals_lead
        FOREIGN KEY (lead_id) REFERENCES leads(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_proposals_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants(id)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
